# What is PyTorch?

- https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#

In [1]:
import torch

In [2]:
print('PyTorch version: %s' % torch.__version__)

PyTorch version: 1.3.0a0


## Tensors

In [3]:
# x = torch.empty(5, 3)
x = torch.rand(5, 3)
print(x)

tensor([[0.3192, 0.5491, 0.5127],
        [0.2557, 0.3751, 0.5907],
        [0.1726, 0.9201, 0.1829],
        [0.7907, 0.6813, 0.0359],
        [0.8529, 0.0388, 0.4503]])


In [4]:
x = torch.empty(5, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [5]:
y = torch.rand(5, 3)
print(y)

tensor([[0.7876, 0.7361, 0.9844],
        [0.4114, 0.1812, 0.2110],
        [0.8866, 0.2092, 0.8540],
        [0.3484, 0.7732, 0.2019],
        [0.5150, 0.9544, 0.6582]])


In [6]:
print(x + y)

tensor([[0.7876, 0.7361, 0.9844],
        [0.4114, 0.1812, 0.2110],
        [0.8866, 0.2092, 0.8540],
        [0.3484, 0.7732, 0.2019],
        [0.5150, 0.9544, 0.6582]])


In [7]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [8]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)    

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.8625, -0.7952, -0.6572],
        [-0.5592,  0.8185, -0.2666],
        [ 0.9961, -0.3273,  1.7124],
        [-1.5271,  0.7727, -1.2612],
        [ 0.3530,  0.6837, -0.7827]])


In [9]:
print(x.size())

torch.Size([5, 3])


In [10]:
x = torch.tensor([])

In [11]:
print(x)

tensor([])


## Operations

In [13]:
x = x.new_ones(5, 3)
y = torch.rand(5, 3)
print(x + y)

tensor([[1.7655, 1.5564, 1.1812],
        [1.4095, 1.7981, 1.0925],
        [1.8716, 1.4441, 1.0973],
        [1.4253, 1.2921, 1.7026],
        [1.3038, 1.3064, 1.9717]])


In [14]:
print(torch.add(x, y))

tensor([[1.7655, 1.5564, 1.1812],
        [1.4095, 1.7981, 1.0925],
        [1.8716, 1.4441, 1.0973],
        [1.4253, 1.2921, 1.7026],
        [1.3038, 1.3064, 1.9717]])


In [15]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[1.7655, 1.5564, 1.1812],
        [1.4095, 1.7981, 1.0925],
        [1.8716, 1.4441, 1.0973],
        [1.4253, 1.2921, 1.7026],
        [1.3038, 1.3064, 1.9717]])


In [16]:
z = x + y

In [17]:
print(z)

tensor([[1.7655, 1.5564, 1.1812],
        [1.4095, 1.7981, 1.0925],
        [1.8716, 1.4441, 1.0973],
        [1.4253, 1.2921, 1.7026],
        [1.3038, 1.3064, 1.9717]])


In [18]:
y.add_(x)
print(y)

tensor([[1.7655, 1.5564, 1.1812],
        [1.4095, 1.7981, 1.0925],
        [1.8716, 1.4441, 1.0973],
        [1.4253, 1.2921, 1.7026],
        [1.3038, 1.3064, 1.9717]])


In [19]:
print(x[:, 1])

tensor([1., 1., 1., 1., 1.])


In [20]:
print(x[1,:])

tensor([1., 1., 1.])


In [21]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [22]:
print(y)

tensor([-0.0278,  1.2208,  0.3374, -0.0067,  1.3516, -1.1105,  2.2308,  0.6927,
        -0.4960, -0.2991, -0.5658, -0.6942,  3.6726, -1.2646, -1.4361,  0.9168])


In [23]:
print(z)

tensor([[-0.0278,  1.2208,  0.3374, -0.0067,  1.3516, -1.1105,  2.2308,  0.6927],
        [-0.4960, -0.2991, -0.5658, -0.6942,  3.6726, -1.2646, -1.4361,  0.9168]])
